### ISSUE TITLE
How to extend the dictionary

### ISSUE THREAD

**Issue by Majokiki** [shihono/alphabet2kana#14]
Is it possible to add external english2kanji data? 

Thanks a lot 🤗

**Comment by shihono** [comment]
Does *english2kanji data* means dictionary like [Kana to kanji conversion](https://en.wikipedia.org/wiki/Japanese_input_method#Kana_to_kanji_conversion)?  

alphabet2kana dictionary data is only for one-to-one conversions.  e.g., `a` is `エー`, `0` is `ゼロ`.
Conversion to Kanji, including Hiragana, Katakana, can not be uniquely identify.  e.g., `a` can convert  `あ`,  `ア`,  `阿`,  `亜`, etc.
